version: "3.1"

services:
  database:
    image: postgres:latest
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=dev123456"
      - "POSTGRES_DB=postgres"
    ports:
      - 5441:5432
    volumes:
      # - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
 
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
volumes:
  pg-data: